# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-26 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=20)),
                ('Balance', models.DecimalField(decimal_places=1, max_digits=5)),
                ('income', models.DecimalField(decimal_places=1, max_digits=5)),
                ('pay', models.DecimalField(decimal_places=1, max_digits=5)),
                ('des', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Balance', models.DecimalField(decimal_places=1, max_digits=5)),
                ('income', models.DecimalField(decimal_places=1, max_digits=5)),
                ('pay', models.DecimalField(decimal_places=1, max_digits=5)),
                ('des', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='成员名字', max_length=20)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('position', models.TextField()),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('number', models.CharField(blank=True, max_length=10, null=True)),
                ('like', models.TextField(blank=True, null=True)),
                ('saying', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
