# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-26 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YPFC', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='age',
        ),
        migrations.AddField(
            model_name='member',
            name='both',
            field=models.DateField(default='1980-01-01'),
        ),
    ]
