# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-27 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YPFC', '0002_auto_20161226_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(default='name', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='position',
            field=models.CharField(default='GK', max_length=20),
        ),
    ]
