# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-27 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YPFC', '0003_auto_20161227_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cash',
            name='Balance',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='Balance',
        ),
    ]
