# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-29 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YPFC', '0006_remove_cash_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[(1, '在队'), (0, '离队')], default='1', max_length=2),
        ),
    ]
