# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-22 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=10)),
                ('args', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
