# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-14 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdata',
            name='error',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sdata',
            name='message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
