# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-15 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_id', models.IntegerField()),
                ('res', models.DecimalField(decimal_places=3, max_digits=6)),
                ('rpm', models.DecimalField(decimal_places=3, max_digits=10)),
                ('create_time', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(default='api.com.', max_length=100)),
                ('version', models.CharField(default='1.0.0', max_length=10)),
                ('des', models.CharField(blank=True, default='接口描述', max_length=100, null=True)),
                ('type', models.CharField(blank=True, default='品类', max_length=100, null=True)),
                ('enabled', models.CharField(default='1', max_length=1)),
            ],
        ),
    ]
