# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-18 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobra', '0005_dayindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayindex',
            name='day',
            field=models.DateField(blank=True),
            preserve_default=False,
        ),
    ]
