#!/bin/bash

#清理intest fzsdata数据，清理前天的，保留昨天的用于偶尔测试
#now=`date '+%Y-%m-%d %H:%M:%S'`
#mysql -plvmama intest -e 'delete from fz_sdata where timestamp < "$now"'


d=`date '+%Y-%m-%d'`

pushd /rd/databack/ServerDBbackup
# 先删掉 30 天之前的数据
currentDate=`date +%s`
expired=15
for x in `find . -name *.zip`
do
modifyDate=`stat -c %Y ${x}`
ExistTime=(${currentDate} - ${modifyDate})/86400
if [[ ${ExistTime} -gt ${expired} ]]
then
svn delete ${x}
rm -f ${x}
else
    echo 'pass'
fi
done

# 备份今天的并且上传到svn
mysqldump -plvmama intest > intest.sql
mysqldump -plvmama mywiki > mywiki.sql
zip -m ${d} *.sql
svn add *
svn commit -m 'DB备份'
popd

exit 0
