#!/bin/bash

#清理intest fzsdata数据，清理前天的，保留昨天的用于偶尔测试
now=`date '+%Y-%m-%d %H:%M:%S'`
mysql -plvmama intest -e 'delete from fz_sdata where timestamp < "$now"'
pushd /rd/监控脚本/ServerDBbackup
mysqldump -plvmama lmmpicTest > lmmpicTest.sql
mysqldump -plvmama tingyun > tingyun.sql
mysqldump -plvmama intest > intest.sql
svn add *
svn commit -m 'DB备份'
popd

#备份intest
#/root/.pyenv/versions/3.5.1/bin/python3 manage.py dumpdata intest > /rd/pystudy/myweb/intest/db/intest.json

#导入
#python manage.py loaddata /rd/pystudy/myweb/intest/db/intest.json

