#!/bin/bash
pushd /rd/pystudy/Intest/myweb/
/root/.pyenv/versions/3.5.1/bin/python3 manage.py dumpdata intest > /rd/pystudy/Intest/myweb/intest/db/intest.json
/root/.pyenv/versions/3.5.1/bin/python3 manage.py dumpdata intest > /rd/pystudy/myweb/intest/db/intest.json
popd

#导入
#python manage.py loaddata /rd/pystudy/myweb/intest/db/intest.json
