# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-22 10:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='caseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(blank=True, max_length=100)),
                ('type_field', models.CharField(blank=True, max_length=100)),
                ('modify_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
