# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-22 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='caseList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseName', models.CharField(blank=True, max_length=100)),
                ('plantform', models.CharField(blank=True, max_length=100)),
                ('version', models.CharField(blank=True, max_length=100)),
                ('case', models.TextField(blank=True)),
                ('in_use', models.CharField(choices=[('1', '在用'), ('0', '废弃')], default='1', max_length=2)),
                ('type_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.caseType')),
            ],
        ),
    ]
