# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-22 17:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_caselist'),
    ]

    operations = [
        migrations.AddField(
            model_name='caselist',
            name='modify_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
