# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-23 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_caselist_modify_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='controlList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controlName', models.CharField(max_length=100)),
                ('controlFiled', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='caselist',
            name='case',
        ),
        migrations.AlterField(
            model_name='caselist',
            name='caseName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='caselist',
            name='plantform',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='caselist',
            name='version',
            field=models.CharField(max_length=100),
        ),
    ]
