# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-23 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0004_auto_20170123_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='controllist',
            name='controlType',
            field=models.CharField(choices=[('0', 'Android'), ('1', 'IOS'), ('2', 'M')], default='0', max_length=2),
        ),
    ]
