# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-08 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0005_controllist_controltype'),
    ]

    operations = [
        migrations.AddField(
            model_name='controllist',
            name='TYPE',
            field=models.CharField(default='action', max_length=100),
        ),
    ]
