# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-09 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0006_controllist_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='caselist',
            name='case',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caselist',
            name='des',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
