# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-23 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0007_auto_20170209_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='caselist',
            name='owner',
            field=models.CharField(default='管理员', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caselist',
            name='caseName',
            field=models.CharField(max_length=300),
        ),
    ]
