# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-23 13:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0008_auto_20170223_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caselist',
            name='des',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='caselist',
            name='modify_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
