# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-24 19:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0009_auto_20170223_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='myConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseStr', models.TextField()),
                ('modify_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
