# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-24 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0010_myconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='myconfig',
            name='device',
            field=models.CharField(default='62001', max_length=100),
            preserve_default=False,
        ),
    ]
