# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-03 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0012_caseuser_caseversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='controllist',
            name='versionStr',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='automation.caseVersion'),
            preserve_default=False,
        ),
    ]
