# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-03 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0013_controllist_versionstr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controllist',
            name='controlFiled',
            field=models.CharField(max_length=300),
        ),
    ]
