# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-17 19:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0014_auto_20170303_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='deviceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceName', models.CharField(max_length=100)),
                ('deviceIP', models.CharField(blank=True, default='127.0.0.1:port', max_length=100)),
                ('APPIUMSERVERSTART', models.CharField(blank=True, max_length=100)),
                ('appiumServicePort', models.IntegerField(blank=True)),
                ('lvsessionid', models.CharField(blank=True, max_length=100)),
                ('job_name', models.CharField(blank=True, default='AndroidAppiumAutoTest', max_length=100)),
                ('appiumServicePath', models.CharField(blank=True, default='10.113.2.70', max_length=20)),
                ('appVersion', models.CharField(blank=True, default='7.8.5', max_length=10)),
                ('appPackage', models.CharField(blank=True, default='com.gift.android', max_length=20)),
                ('platformVersion', models.CharField(blank=True, default='4.4.2', max_length=10)),
                ('appLaunchActivity', models.CharField(blank=True, default='com.gift.android.activity.splash.WelcomeActivity', max_length=100)),
                ('timeWait', models.IntegerField(blank=True, default=30)),
            ],
        ),
        migrations.CreateModel(
            name='secondType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_Type', models.CharField(default='测试', max_length=100)),
                ('modify_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
