# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-20 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0016_auto_20170317_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='caselist',
            name='second_Type',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='automation.secondType'),
            preserve_default=False,
        ),
    ]
