# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-20 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0017_caselist_second_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='reportsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.CharField(max_length=200)),
                ('buildNUM', models.CharField(blank=True, max_length=20)),
                ('reportURL', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
