# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-20 14:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0018_reportslist'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportslist',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
