# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-20 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0019_reportslist_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportslist',
            name='deviceName',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='automation.deviceList'),
            preserve_default=False,
        ),
    ]
