# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-22 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0020_reportslist_devicename'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelist',
            name='in_use',
            field=models.CharField(choices=[('1', '启用'), ('0', '禁用')], default='1', max_length=2),
        ),
    ]
