# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-29 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0022_devicelist_platformname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportslist',
            name='timeStamp',
            field=models.TextField(),
        ),
    ]
