# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-05 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0023_auto_20170329_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='allBookRecording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseName', models.CharField(max_length=300)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('testResultDoc', models.TextField()),
                ('timeStamp', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='testRecording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testStartDate', models.DateTimeField()),
                ('testCondition', models.CharField(max_length=100)),
                ('testDuration', models.DateTimeField()),
                ('testAppVersion', models.CharField(max_length=100)),
                ('timeStamp', models.CharField(max_length=100)),
            ],
        ),
    ]
