# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-06 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0024_allbookrecording_testrecording'),
    ]

    operations = [
        migrations.AddField(
            model_name='allbookrecording',
            name='usedTime',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
