# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-07 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0025_allbookrecording_usedtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controllist',
            name='versionStr',
        ),
        migrations.AddField(
            model_name='controllist',
            name='versionStr',
            field=models.ManyToManyField(to='automation.caseVersion'),
        ),
    ]
