# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-24 16:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0026_auto_20170407_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='caseGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(max_length=300)),
                ('caseID', models.TextField()),
                ('des', models.TextField()),
                ('status', models.CharField(choices=[('0', '禁用'), ('1', '启用')], default='1', max_length=2)),
                ('modify_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='devicelist',
            name='adbPort',
            field=models.CharField(blank=True, default='9000', max_length=100),
        ),
    ]
