# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-11 16:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0027_auto_20170424_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='allbookrecording',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
