# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-16 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0028_allbookrecording_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelist',
            name='password',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='devicelist',
            name='url',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='devicelist',
            name='username',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
