# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-22 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0029_auto_20170516_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='casegroup',
            name='versionStr',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='automation.caseVersion'),
        ),
    ]
