# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-23 15:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0030_casegroup_versionstr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrecording',
            name='testAppVersion',
        ),
        migrations.RemoveField(
            model_name='testrecording',
            name='testCondition',
        ),
        migrations.RemoveField(
            model_name='testrecording',
            name='testDuration',
        ),
        migrations.RemoveField(
            model_name='testrecording',
            name='testStartDate',
        ),
        migrations.AddField(
            model_name='testrecording',
            name='Version',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='testrecording',
            name='createTime',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='caselist',
            name='modify_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
