# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-26 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0031_auto_20170523_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrecording',
            name='groupId',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
