# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-27 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0032_testrecording_groupid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allbookrecording',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='casegroup',
            name='modify_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='casetype',
            name='modify_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='myconfig',
            name='modify_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reportslist',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='secondtype',
            name='modify_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='testrecording',
            name='createTime',
            field=models.DateField(auto_now=True),
        ),
    ]
