# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-11 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0033_auto_20170527_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicelist',
            name='in_use',
            field=models.CharField(choices=[('1', '启用'), ('0', '禁用'), ('2', '测试用')], default='1', max_length=2),
        ),
    ]
