# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-25 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0034_auto_20170711_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelist',
            name='bundleId',
            field=models.CharField(blank=True, default='iOS use', max_length=200),
        ),
        migrations.AddField(
            model_name='devicelist',
            name='webDriverAgentUrl',
            field=models.CharField(blank=True, default='iOS use', max_length=200),
        ),
        migrations.AlterField(
            model_name='devicelist',
            name='APPIUMSERVERSTART',
            field=models.CharField(blank=True, default='AD use', max_length=200),
        ),
        migrations.AlterField(
            model_name='devicelist',
            name='adbPort',
            field=models.CharField(blank=True, default='AD use', max_length=10),
        ),
        migrations.AlterField(
            model_name='devicelist',
            name='appPackage',
            field=models.CharField(blank=True, default='com.gift.android', max_length=200),
        ),
        migrations.AlterField(
            model_name='devicelist',
            name='appVersion',
            field=models.CharField(blank=True, default='7.9.3', max_length=10),
        ),
        migrations.AlterField(
            model_name='devicelist',
            name='appiumServicePath',
            field=models.CharField(blank=True, default='eg:10.113.2.70', max_length=20),
        ),
        migrations.AlterField(
            model_name='devicelist',
            name='password',
            field=models.CharField(blank=True, default='for jenkins', max_length=100),
        ),
        migrations.AlterField(
            model_name='devicelist',
            name='platformName',
            field=models.CharField(blank=True, default='Android or iOS', max_length=20),
        ),
        migrations.AlterField(
            model_name='devicelist',
            name='platformVersion',
            field=models.CharField(blank=True, default='4.4.2 or 10.3', max_length=20),
        ),
        migrations.AlterField(
            model_name='devicelist',
            name='url',
            field=models.CharField(blank=True, default='for jenkins', max_length=100),
        ),
        migrations.AlterField(
            model_name='devicelist',
            name='username',
            field=models.CharField(blank=True, default='for jenkins', max_length=100),
        ),
    ]
