# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-15 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0037_devicelist_udid'),
    ]

    operations = [
        migrations.CreateModel(
            name='caseTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagName', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='caselist',
            name='second_Type',
        ),
        migrations.AddField(
            model_name='casegroup',
            name='platform',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='caselist',
            name='case_tag',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.DeleteModel(
            name='secondType',
        ),
    ]
