# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-15 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0038_auto_20170815_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='casetag',
            name='type_field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='automation.caseType'),
            preserve_default=False,
        ),
    ]
