# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-02 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0040_myconfig_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allbookrecording',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reportslist',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='testrecording',
            name='createTime',
            field=models.DateField(auto_now_add=True),
        ),
    ]
