# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-05 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0041_auto_20170902_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='caselist',
            name='groupId',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
