# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-05 19:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0042_caselist_groupid'),
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opertionTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('remoteIp', models.CharField(blank=True, max_length=100)),
                ('operton', models.TextField(blank=True)),
            ],
        ),
    ]
