# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-05 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0044_auto_20170905_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='opertion',
            new_name='operation',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='opertionTime',
            new_name='operationTime',
        ),
    ]
