# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-15 14:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0045_auto_20170905_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='userGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(max_length=256, verbose_name='组名')),
                ('groupUser', models.TextField(blank=True, null=True, verbose_name='成员')),
                ('des', models.TextField(blank=True, verbose_name='描述')),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
