# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-15 15:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0046_auto_20170915_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='allbookrecording',
            name='modify_time',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 9, 15, 15, 31, 15, 592647)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casegroup',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 9, 15, 15, 31, 17, 378180)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caselist',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 9, 15, 15, 31, 18, 629731)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casetag',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 9, 15, 15, 31, 19, 666535)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casetag',
            name='modify_time',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 9, 15, 15, 31, 24, 433615)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casetype',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 9, 15, 15, 31, 25, 536876)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caseuser',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 9, 15, 15, 31, 28, 538106)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caseuser',
            name='modify_time',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 9, 15, 15, 31, 29, 522829)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caseversion',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 9, 15, 15, 31, 30, 634789)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caseversion',
            name='modify_time',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 9, 15, 15, 31, 31, 905811)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='controllist',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 9, 15, 15, 31, 33, 73601)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='controllist',
            name='modify_time',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 9, 15, 15, 31, 33, 987318)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicelist',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 9, 15, 15, 31, 35, 258663)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicelist',
            name='modify_time',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 9, 15, 15, 31, 36, 625600)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myconfig',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 9, 15, 15, 31, 37, 603374)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportslist',
            name='modify_time',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 9, 15, 15, 31, 38, 779727)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testrecording',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 9, 15, 15, 31, 39, 916419)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testrecording',
            name='modify_time',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 9, 15, 15, 31, 41, 276367)),
            preserve_default=False,
        ),
    ]
