# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-15 18:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0048_remove_testrecording_createtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allbookrecording',
            name='modify_time',
        ),
    ]
