# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-16 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0049_remove_allbookrecording_modify_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrecording',
            name='create_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
