# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-20 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0050_auto_20170916_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='allbookrecording',
            name='caseID',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
