# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-22 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0051_allbookrecording_caseid'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrecording',
            name='status',
            field=models.CharField(blank=True, max_length=10, verbose_name='用例集构建状态'),
        ),
    ]
