# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-29 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0052_testrecording_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='caselist',
            name='buildTime',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
