# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-29 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0053_caselist_buildtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caselist',
            name='case_tag',
        ),
        migrations.RemoveField(
            model_name='casetype',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='casetype',
            name='modify_time',
        ),
        migrations.RemoveField(
            model_name='casetype',
            name='type_field',
        ),
        migrations.RemoveField(
            model_name='myconfig',
            name='modify_time',
        ),
    ]
